name: claudebox

services:
  claudebox:
    build:
      context: https://github.com/RchGrav/claudebox.git#main
      dockerfile: Dockerfile
    image: claudebox:latest
    volumes:
      - claudebox-data:/workspace
      - claudebox-home:/home/user
    environment:
      - TERM=xterm-256color
    working_dir: /workspace
    tty: true
    stdin_open: true
    networks:
      - dokploy-network
    command: >
      /bin/bash -c "
        pacman -Syu --noconfirm &&
        pacman -S --noconfirm curl sudo nodejs npm git &&
        useradd -m -s /bin/bash user &&
        echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/user &&
        su - user -c '
          npm install -g @anthropic-ai/claude-code &&
          npm install -g claude-flow@alpha &&
          claude-flow init --force --hive-mind --neural-enhanced &&
          claude-flow mcp setup --auto-permissions --87-tools &&
          /bin/bash
        '
      "

volumes:
  claudebox-data:
  claudebox-home:

networks:
  dokploy-network:
    external: true
